#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define DEFAULT_MAP_WIDTH 96
#define DEFAULT_MAP_HEIGHT 30
#define MAX_MAP_WIDTH DEFAULT_MAP_WIDTH
#define MAX_MAP_HEIGHT DEFAULT_MAP_HEIGHT

#define MAX_ENEMIES 96
#define MAX_PROJECTILES 96
#define MAX_PICKUPS 256
#define UPGRADE_CHOICES 3
#define MAX_RANKINGS 5
#define MAX_NAME_LEN 15

#define SURVIVAL_SECONDS 300.0f  /* 5분 */
#define HP_RECOVERY_SECONDS 60.0f

#endif
